set(BFHTTPECHO_MAJOR_VERSION 1)
set(BFHTTPECHO_MINOR_VERSION 0)
set(BFHTTPECHO_PATCH_VERSION 0)

set(BFHTTPECHO_VERSION ${BFHTTPECHO_MAJOR_VERSION}.${BFHTTPECHO_MINOR_VERSION}.${BFHTTPECHO_PATCH_VERSION})

message(STATUS "Building bfhttpecho version ${BFHTTPECHO_VERSION}")
